import 'package:test/test.dart';
import 'package:conekta/conekta.dart';


/// tests for PaymentLinkApi
void main() {
  final instance = Conekta().getPaymentLinkApi();

  group(PaymentLinkApi, () {
    // Cancel Payment Link
    //
    //Future<CheckoutResponse> cancelCheckout(String id, { String acceptLanguage, String xChildCompanyId }) async
    test('test cancelCheckout', () async {
      // TODO
    });

    // Create Unique Payment Link
    //
    //Future<CheckoutResponse> createCheckout(Checkout checkout, { String acceptLanguage, String xChildCompanyId }) async
    test('test createCheckout', () async {
      // TODO
    });

    // Send an email
    //
    //Future<CheckoutResponse> emailCheckout(String id, EmailCheckoutRequest emailCheckoutRequest, { String acceptLanguage, String xChildCompanyId }) async
    test('test emailCheckout', () async {
      // TODO
    });

    // Get a payment link by ID
    //
    //Future<CheckoutResponse> getCheckout(String id, { String acceptLanguage, String xChildCompanyId }) async
    test('test getCheckout', () async {
      // TODO
    });

    // Get a list of payment links
    //
    // Returns a list of links generated by the merchant
    //
    //Future<CheckoutsResponse> getCheckouts({ String acceptLanguage, String xChildCompanyId, int limit, String search, String next, String previous }) async
    test('test getCheckouts', () async {
      // TODO
    });

    // Send an sms
    //
    //Future<CheckoutResponse> smsCheckout(String id, SmsCheckoutRequest smsCheckoutRequest, { String acceptLanguage, String xChildCompanyId }) async
    test('test smsCheckout', () async {
      // TODO
    });

  });
}
