name: conekta
version: 6.0.2
description: A simple Conekta API wrapper, that is meant to be used on the server.
homepage: https://www.github.com/conekta/conekta-dart
repository: https://www.github.com/conekta/conekta-dart

environment:
  sdk: '>=2.15.0 <3.0.0'

dependencies:
  dio: '^5.2.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'
  meta: 1.9.1

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: ^1.16.0
